#ifndef __TRAP_H__
#define __TRAP_H__
#pragma once
enum EXCEPTION_TYPE
{
    INSTRUCTION_ADDRESS_MISALIGNED = 0,
    INSTRUCTION_ACCESS_FAULT = 1,
    ILLEGAL_INSTRUCTION = 2,
    BREAKPOINT = 3,
    LOAD_ADDRESS_MISALIGNED = 4,
    LOAD_ACCESS_FAULT = 5,
    STORE_AMO_ADDRESS_MISALIGN = 6,
    STORE_AMO_ACCESS_FAULT = 7,
    ECALL_FROM_U_MODE = 8,
    ECALL_FROM_S_MODE = 9,
    RESERVED = 10,
    ECALL_FROM_M_MODE = 11,
    INSTRUCTION_PAGE_FAULT = 12,
    LOAD_PAGE_FAULT = 13,
    RESERVED_FOR_FUTURE = 14,
    STORE_AMO_PAGE_FAULT = 15,
    EXCEPTION_TYPE_NUM = 16,
};

#endif /* __TRAP_H__ */